### ISSUE TITLE
问一下提示“您所在地区不可观看”怎么解决

### ISSUE THREAD

**Issue by JSTks24** [JasonKhew96/biliroaming-go-server-docker#1]
如题
在隔壁那个go弄了半天之后，我觉得还是docker好弄，就来搞了一下
弄完之后测试了一下，直接访问域名能看到我留下的index.html
但是在进番剧的时候，却提示您所在的地区不可看
我的服务器确实是处于香港的，之前用过php版的，但是那个在我换域名之后响应变得特别慢，就来试试这个

**Comment by JasonKhew96** [comment]
得看你的设置怎么配置的，地区 proxy 留空就是 直连
如果是自己用的，建议直接 nginx 反代 就可以了，多人用才用 特殊后端 处理 并 缓存

如果还是不清楚哪里出问题，打开 debug 查 log

**Comment by JSTks24** [comment]
> 得看你的设置怎么配置的，地区 proxy 留空就是 直连 如果是自己用的，建议直接 nginx 反代 就可以了，多人用才用 特殊后端 处理 并 缓存
> 
> 如果还是不清楚哪里出问题，打开 debug 查 log

问一下这里所说的更改password文件是什么意思，docker的话是不会访问我主机的数据库吧，那这个密码要改成什么？

> 修改 PostgreSQL 数据库密码 db/password.txt

我最初的时候更改了端口，因为我80和443被本地的Nginx占用了，我就修改了一下端口然后用Nginx代理了一下域名指向端口，这个会影响我那个地区问题吗？

**Comment by JasonKhew96** [comment]
> 问一下这里所说的更改password文件是什么意思，docker的话是不会访问我主机的数据库吧，那这个密码要改成什么？

https://github.com/JasonKhew96/biliroaming-go-server-docker/blob/5ffacf596acc4ba1fa365d4fe8c4e575bc14b87d/config/config.example.yml#L100

这里对应这个文件吧 `db/password.txt`

其实可以不改，外部 应该不能 访问 内部数据库，`docker exec` 查数据库用


> 我最初的时候更改了端口，因为我80和443被本地的Nginx占用了，我就修改了一下端口然后用Nginx代理了一下域名指向端口，这个会影响我那个地区问题吗？

如果你有外部 `nginx`，建议直接用外部的 `docker-compose.yml`
外部 nginx 直接反代到 docker 端口，docker 端口这里改，改左边那个，右边的要对应 `config/config.yml`

https://github.com/JasonKhew96/biliroaming-go-server-docker/blob/5ffacf596acc4ba1fa365d4fe8c4e575bc14b87d/docker-compose.yml#L11-L13

**Comment by JSTks24** [comment]
> > 问一下这里所说的更改password文件是什么意思，docker的话是不会访问我主机的数据库吧，那这个密码要改成什么？
> 
> https://github.com/JasonKhew96/biliroaming-go-server-docker/blob/5ffacf596acc4ba1fa365d4fe8c4e575bc14b87d/config/config.example.yml#L100
> 
> 这里对应这个文件吧 `db/password.txt`
> 
> 其实可以不改，外部 应该不能 访问 内部数据库，`docker exec` 查数据库用
> 
> > 我最初的时候更改了端口，因为我80和443被本地的Nginx占用了，我就修改了一下端口然后用Nginx代理了一下域名指向端口，这个会影响我那个地区问题吗？
> 
> 如果你有外部 `nginx`，建议直接用外部的 `docker-compose.yml` 外部 nginx 直接反代到 docker 端口，docker 端口这里改，改左边那个，右边的要对应 `config/config.yml`
> 
> https://github.com/JasonKhew96/biliroaming-go-server-docker/blob/5ffacf596acc4ba1fa365d4fe8c4e575bc14b87d/docker-compose.yml#L11-L13

是的，我就是用这样的方式修改了端口，然后使用Nginx反代

我重新部署了这个项目，没有变更任何东西，但是却出现了报错
`{"level":"info","ts":1659858148.822775,"caller":"builder/main.go:231","msg":"Version: v2.16.0"}
{"level":"fatal","ts":1659858148.8304217,"caller":"builder/main.go:276","msg":"pq: password authentication failed for user \"postgres\"","stacktrace":"main.main\n\t/tmp/builder/main.go:276\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"info","ts":1659858149.5067742,"caller":"builder/main.go:231","msg":"Version: v2.16.0"}
{"level":"fatal","ts":1659858149.5138004,"caller":"builder/main.go:276","msg":"pq: password authentication failed for user \"postgres\"","stacktrace":"main.main\n\t/tmp/builder/main.go:276\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"info","ts":1659858150.1459754,"caller":"builder/main.go:231","msg":"Version: v2.16.0"}
{"level":"fatal","ts":1659858150.1528046,"caller":"builder/main.go:276","msg":"pq: password authentication failed for user \"postgres\"","stacktrace":"main.main\n\t/tmp/builder/main.go:276\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"info","ts":1659858150.9448557,"caller":"builder/main.go:231","msg":"Version: v2.16.0"}
{"level":"fatal","ts":1659858150.9521327,"caller":"builder/main.go:276","msg":"pq: password authentication failed for user \"postgres\"","stacktrace":"main.main\n\t/tmp/builder/main.go:276\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"info","ts":1659858152.146387,"caller":"builder/main.go:231","msg":"Version: v2.16.0"}
{"level":"fatal","ts":1659858152.1538813,"caller":"builder/main.go:276","msg":"pq: password authentication failed for user \"postgres\"","stacktrace":"main.main\n\t/tmp/builder/main.go:276\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"info","ts":1659858154.155898,"caller":"builder/main.go:231","msg":"Version: v2.16.0"}
{"level":"fatal","ts":1659858154.1629388,"caller":"builder/main.go:276","msg":"pq: password authentication failed for user \"postgres\"","stacktrace":"main.main\n\t/tmp/builder/main.go:276\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}`

我在第一次部署这个项目的时候在本地也创建了pgsql的库并且修改了文件中的用户名密码，后来我把它删了

**Comment by JasonKhew96** [comment]
![image](https://user-images.githubusercontent.com/29531167/183280960-8ea77a52-92ed-4b37-a831-7ca5fb367d0e.png)
这个别改

**Comment by JSTks24** [comment]
> > 问一下这里所说的更改password文件是什么意思，docker的话是不会访问我主机的数据库吧，那这个密码要改成什么？
> 
> https://github.com/JasonKhew96/biliroaming-go-server-docker/blob/5ffacf596acc4ba1fa365d4fe8c4e575bc14b87d/config/config.example.yml#L100
> 
> 这里对应这个文件吧 `db/password.txt`
> 
> 其实可以不改，外部 应该不能 访问 内部数据库，`docker exec` 查数据库用
> 
> > 我最初的时候更改了端口，因为我80和443被本地的Nginx占用了，我就修改了一下端口然后用Nginx代理了一下域名指向端口，这个会影响我那个地区问题吗？
> 
> 如果你有外部 `nginx`，建议直接用外部的 `docker-compose.yml` 外部 nginx 直接反代到 docker 端口，docker 端口这里改，改左边那个，右边的要对应 `config/config.yml`
> 
> https://github.com/JasonKhew96/biliroaming-go-server-docker/blob/5ffacf596acc4ba1fa365d4fe8c4e575bc14b87d/docker-compose.yml#L11-L13

另外就是您在[biliroaming-go-server](https://github.com/JasonKhew96/biliroaming-go-server)中./biliroaming-go-server这个指令，我没有在目录下找到对应的执行文件，是因为go语言需要编译吗？

**Comment by JasonKhew96** [comment]
预编译了，https://github.com/JasonKhew96/biliroaming-go-server/blob/main/.github/workflows/docker.yml
除了配置文件，全都在 容器 里

**Comment by JSTks24** [comment]
> 预编译了，https://github.com/JasonKhew96/biliroaming-go-server/blob/main/.github/workflows/docker.yml 除了配置文件，全都在 容器 里

好的，我这边再试试，打扰您了
