### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by lolikyo** [JasonKhew96/biliroaming-go-server-docker#2]
```{"level":"error","ts":1673160740.5811954,"caller":"builder/playurl.go:248","msg":"models: unable to upsert play_url_caches: pq: null value in column \"quality\" of relation \"play_url_caches\" violates not-null constraint","stacktrace":"main.(*BiliroamingGo).handleAndroidPlayURL\n\t/tmp/builder/playurl.go:248\nmain.initHttpServer.func1\n\t/tmp/builder/main.go:194\ngithub.com/valyala/fasthttp.(*Server).serveConn\n\t/go/pkg/mod/github.com/valyala/fasthttp@v1.35.0/server.go:2338\ngithub.com/valyala/fasthttp.(*workerPool).workerFunc\n\t/go/pkg/mod/github.com/valyala/fasthttp@v1.35.0/workerpool.go:224\ngithub.com/valyala/fasthttp.(*workerPool).getCh.func1\n\t/go/pkg/mod/github.com/valyala/fasthttp@v1.35.0/workerpool.go:196"}```

curl http://api.bilibili.com/x/web-interface/zone 的结果
```{"code":0,"message":"0","ttl":1,"data":{"addr":"*****8","country":"香港","isp":"amazon.com","latitude":*****,"longitude":******,"zone_id":******,"country_code":852}}```

直接挂v2到节点能看

**Comment by JasonKhew96** [comment]
数据库出问题了，怪了

**Comment by lolikyo** [comment]
谢谢，down移除重新build好了

**Comment by 666dechaoge** [comment]
重新部署又崩了，docker镜像在今天似乎更新了
#### DB
```2023-01-15 09:42:54.141 UTC [33] ERROR:  relation "play_url_caches" does not exist
2023-01-15 09:42:54.141 UTC [33] STATEMENT:  ALTER TABLE play_url_caches 
	DROP COLUMN IF EXISTS cid
```
#### Server
```{"level":"fatal","ts":1673775942.6550405,"caller":"builder/main.go:278","msg":"pq: relation \"play_url_caches\" does not exist handling 0003-drop-cid-support.sql","stacktrace":"main.main\n\t/tmp/builder/main.go:278\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}```

**Comment by JasonKhew96** [comment]
哎，没时间维护 docker 镜像...

**Comment by lolikyo** [comment]
> 哎，没时间维护 docker 镜像...

没事了，我把数据卷移除，重新compose了下好像就好了
