### ISSUE TITLE
提示账号未登录

### ISSUE THREAD

**Issue by sizxiwu** [JasonKhew96/biliroaming-go-server-docker#3]
手机上也重新登录好几次
我换了好几个服务器都一样.
用php版太慢了.
![image](https://user-images.githubusercontent.com/121373708/225551598-c16a0821-5c83-4355-87ed-668c60bbc9e2.png)
![image](https://user-images.githubusercontent.com/121373708/225551670-1bb56bf2-5523-4ce9-9b5e-3c3bc07d6372.png)
![image](https://user-images.githubusercontent.com/121373708/225551741-4a65b0d0-529b-4496-9b4f-8368f415f267.png)
![image](https://user-images.githubusercontent.com/121373708/225552244-7540754f-7c55-46e8-85d0-5ea791043385.png)

**Comment by JasonKhew96** [comment]
没搞懂，backend 日志给得不够详细
请确保 后端 跟 漫游 都是 新版，漫游 请务必用 CI 版

**Comment by sizxiwu** [comment]
更新哔哩哔哩就可以vv
